---
title: "Functions"
output: 
  learnr::tutorial:
     allow_skip: true
tutorial:
  id: "io.shinyapps.erasmusmc.BST02functions1"
  version: 0.900
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library("learnr")
library('BST02R')
data("pain", package = "BST02R")
knitr::opts_chunk$set(echo = FALSE)
```



## Exercises (p1)

We want to create a function that takes a data frame as input and selects all rows for which a certain variable ('age' by default) inside the data set is above a cutoff value (65 by default).

Complete the function:
```{r P1, exercise=TRUE, exercise.lines = 16, eval=FALSE}
myfn <-
function(dataset, varname='age', cutoff=65){

  return(rv)  
}
myfn(pain, 'age')
```

```{r P1-hint-1}
myfn <-
function(dataset, varname='age', cutoff=65){
  rv <- dataset[..., ]  # figure out what should be on the ...
  return(rv)
}
myfn(pain, 'age')
```
```{r P1-hint-2}
myfn <-
function(dataset, varname='age', cutoff=65){
  rv <- dataset[dataset[,...]>..., ]  
  # figure out what should be on the ...
  return(rv)
}
myfn(pain, 'age')
```


```{r P1-hint-3}
# Use:
myfn <- 
function(dataset, varname='age', cutoff=65){
  rv <- dataset[dataset[,varname] > cutoff , ]
  return(rv)
}
```
